export { default as OverviewSection } from "./overview-section";
export { default as ProfileSummary } from "./profile-summary";
export { default as TechnicalSummary } from "./technical-summary";
export { default as AcademicProfile } from "./academic-profile";
export { default as Certificates } from "./certificates";
export { default as ProfessionalExperience } from "./professional-experience";
export { default as Awards } from "./awards";
export { default as CareerMilestones } from "./career-milestones";
export { default as Languages } from "./languages";
